version: '3'

services:

  spring_test4:
    build:
      context: .
    ports:
      - "6060:6060"
    networks:
      - ems_common_network

volumes:
  postgres_data:

networks:
  ems_common_network:
    external: true