version: '3'

services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ems_monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data_monitoring:/var/lib/postgresql/data2
    networks:
      - ems_common_network

  spring_test3:
    build: .
    environment:
      - DB_IP=postgres
      - DB_NAME=ems_monitoring
      - DB_USER=postgres
      - DB_PASSWORD=root
    ports:
      - "4040:4040"
    depends_on:
      - postgres
    networks:
      - ems_common_network

volumes:
  postgres_data_monitoring:

networks:
  ems_common_network:
    external: true
