version: '3.8'

services:
  postgres_device:
    image: postgres
    container_name: postgres_device
    environment:
      POSTGRES_DB: 'ems_devices'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
    ports:
      - "5433:5432"
    volumes:
      - my-db:/var/lib/postgres

  postgres_users:
    image: postgres
    container_name: postgres_users
    environment:
      POSTGRES_DB: 'ems_users'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
    ports:
      - "5434:5432"
    volumes:
      - my-db2:/var/lib/postgres

  users:
    image: user_image
    container_name: users-container
    depends_on:
      - postgres_users
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_users:5432/ems_users
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8081:8080"

  devices:
    image: device_image
    container_name: devices-container
    depends_on:
      - postgres_device
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_device:5432/ems_devices
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "9091:9090"


  chat:
    image: chat_image
    container_name: chat-container
    ports:
      - "1011:1010"

  fe:
    image: frontend_image
    container_name: fe-service
    ports:
      - "3000:3000"
    depends_on:
      - devices
      - users
      - chat


volumes:
  my-db:
  my-db2: