version: '3'

services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ems_devices
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

    volumes:
      - postgres_data_devices:/var/lib/postgresql/data1
    networks:
      - ems_common_network

  spring_test1:
    build: .
    environment:
      - DB_IP=postgres
      - DB_NAME=ems_devices
      - DB_USER=postgres
      - DB_PASSWORD=root
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    networks:
      - ems_common_network


volumes:
  postgres_data_devices:

networks:
  ems_common_network:
    external: true
