version: '3'

services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ems_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - C:\postgres_container_data:/docker-entrypoint-initdb.d

    networks:
      - ems_common_network

  spring_test:
    build: .
    environment:
      - DB_IP=postgres
      - DB_NAME=ems_users
      - DB_USER=postgres
      - DB_PASSWORD=root
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - ems_common_network

volumes:
  postgres_data:

networks:
  ems_common_network:
    external: true